
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
shell_command: !include shell_commands.yaml

zeroconf:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.31.3.51/32

google_assistant:
  project_id: has-integration-52518
  service_account: !include has-integration-52518-449e0a54cc40.json
  expose_by_default: true
  exposed_domains:
    - script

rest_command:
  wake_proxmox:
      url: 'https://172.31.1.1/api/wol/wol/set'
      verify_ssl: false
      method: POST
      payload: '{"wake":{"interface": "lan","mac": "54:a0:50:55:26:85"}}'
      content_type:  'application/json'
      username: !secret opnsense_user
      password: !secret opnsense_key
  wake_nosuchdesktop:
      url: 'https://172.31.1.1/api/wol/wol/set'
      verify_ssl: false
      method: POST
      payload: '{"wake":{"interface": "lan","mac": "D8:BB:C1:91:A7:13"}}'
      content_type:  'application/json'
      username: !secret opnsense_user
      password: !secret opnsense_key

binary_sensor:
  - platform: ping
    host: 172.31.1.7
    name: "proxmox"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 172.31.1.100
    name: "nosuchdesktop"
    count: 2
    scan_interval: 30

switch:
  - platform: template
    switches:
      proxmox:
        unique_id: start-stop proxmox
        value_template: "{{ is_state('binary_sensor.proxmox', 'on') }}"
        turn_on:
          service: rest_command.wake_proxmox
        turn_off:
          service: shell_command.turn_off_proxmox
      nosuchdesktop:
        unique_id: start-stop nosuchdesktop
        value_template: "{{ is_state('binary_sensor.nosuchdesktop', 'on') }}"
        turn_on:
          service: rest_command.wake_nosuchdesktop
        turn_off:
          service: shell_command.turn_off_nosuchdesktop
